#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Set environment variables.
#======================================================================================================================

FILES="/files"
bf-env "SAMBA_FILES" ${FILES}
bf-env "SAMBA_SHARES_CONF" "${FILES}/shares.json"

bf-env "SAMBA_CONF" "/etc/samba/smb.conf"
