#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Set environment variables.
#======================================================================================================================

bf-env "SAMBA_FILES" "/files"
bf-env "SAMBA_CONF" "/etc/smb/smb.conf"
