#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Load shares configuration.
#======================================================================================================================

source ${BF_INC}/samba-load-conf.sh


#======================================================================================================================
# Generate Samba config file.
#======================================================================================================================

bf-esh \
    ${BF_TEMPLATES}/smb.conf.esh \
    ${SAMBA_CONF}


#======================================================================================================================
# Append each share.
#======================================================================================================================

bf-echo "Adding shares..."
for SHARE in "${SAMBA_SHARES[@]}" ; do

    # get config values
    export NAME=${SHARE}
    export COMMENT=`get-comment "${SHARE}"`
    export USERS=`get-users "${SHARE}"`
    export BROWSEABLE=`get-browseable "${SHARE}"`
    export WRITEABLE=`get-writeable "${SHARE}"`
    bf-echo " .. ${NAME}"
    bf-debug "    \"${COMMENT}\" - users: ${USERS}, browseable: ${BROWSEABLE}, writeable: ${WRITEABLE}"

    # use public template if permission is set to "*"
    if [ "${USERS}" = "*" ] ; then
        esh ${BF_TEMPLATES}/public.esh >> ${SAMBA_CONF}
    else
        esh ${BF_TEMPLATES}/share.esh >> ${SAMBA_CONF}
    fi

done
bf-done
