#!/command/with-contenv sh

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Run Samba server.
#======================================================================================================================

[[ ! -f ${SAMBA_CONF} ]] && bf-error "Samba configuration file not found."

bf-echo "Starting vsftpd."
vsftpd ${FTPS_VSFTPD_CONF}
