#!/command/with-contenv bash

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Run Samba server.
#======================================================================================================================

[[ ! -f ${SAMBA_CONF} ]] && bf-error "Samba configuration file not found."

bf-echo "Starting Samba."
smbd --configfile=${SAMBA_CONF} --debug-stdout --foreground
